# Generated by Django 5.1.12 on 2025-09-19 06:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bruker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornavn', models.CharField(max_length=50)),
                ('etternavn', models.CharField(max_length=50)),
                ('telefon', models.CharField(help_text='Telefonnummer med landkode (+47)', max_length=15, unique=True)),
                ('epost', models.EmailField(blank=True, max_length=254, null=True)),
                ('registrert', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bruker',
                'verbose_name_plural': 'Brukere',
                'ordering': ['etternavn', 'fornavn'],
            },
        ),
        migrations.CreateModel(
            name='SkiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(help_text='Navn på ski-elementet', max_length=100)),
                ('type_ski', models.CharField(choices=[('alpinski', 'Alpinski'), ('langrenn', 'Langrennsski'), ('snowboard', 'Snowboard'), ('stovler', 'Skistøvler'), ('staver', 'Skistaver')], help_text='Type ski-element', max_length=20)),
                ('storrelse', models.IntegerField(help_text='Størrelse i cm for ski/staver, EU-størrelse for støvler', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('tilstand', models.CharField(choices=[('utmerket', 'Utmerket'), ('god', 'God'), ('slitt', 'Slitt'), ('reparasjon', 'Trenger reparasjon')], default='god', max_length=20)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('oppdatert', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ski-element',
                'verbose_name_plural': 'Ski-elementer',
                'ordering': ['type_ski', 'storrelse'],
            },
        ),
        migrations.CreateModel(
            name='Utlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utlant_dato', models.DateTimeField(default=django.utils.timezone.now, help_text='Når ble itemet lånt ut')),
                ('planlagt_retur', models.DateField(help_text='Når skal itemet leveres tilbake')),
                ('returnert_dato', models.DateTimeField(blank=True, help_text='Når ble itemet faktisk levert tilbake (tomt = ikke returnert)', null=True)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('bruker', models.ForeignKey(help_text='Hvem som låner', on_delete=django.db.models.deletion.CASCADE, to='skiutlan.bruker')),
                ('ski_item', models.ForeignKey(help_text='Hva som lånes', on_delete=django.db.models.deletion.CASCADE, to='skiutlan.skiitem')),
            ],
            options={
                'verbose_name': 'Utlån',
                'verbose_name_plural': 'Utlån',
                'ordering': ['-utlant_dato'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('returnert_dato__isnull', True)), fields=('ski_item',), name='unique_active_loan_per_item')],
            },
        ),
    ]
