# Generated by Django 5.1.12 on 2025-09-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skiutlan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='utlan',
            name='unique_active_loan_per_item',
        ),
    ]
