# Generated by Django 5.1.12 on 2025-09-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiutlan', '0002_remove_utlan_unique_active_loan_per_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utlan',
            name='utlant_dato',
            field=models.DateTimeField(auto_now_add=True, help_text='Når ble itemet lånt ut'),
        ),
    ]
