# Generated by Django 5.1.12 on 2025-09-19 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiutlan', '0003_alter_utlan_utlant_dato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utlan',
            options={},
        ),
        migrations.RemoveField(
            model_name='utlan',
            name='opprettet',
        ),
        migrations.AlterField(
            model_name='utlan',
            name='bruker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skiutlan.bruker'),
        ),
        migrations.AlterField(
            model_name='utlan',
            name='planlagt_retur',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='utlan',
            name='returnert_dato',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utlan',
            name='ski_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skiutlan.skiitem'),
        ),
        migrations.AlterField(
            model_name='utlan',
            name='utlant_dato',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
