# Generated by Django 5.1.12 on 2025-09-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiutlan', '0004_alter_utlan_options_remove_utlan_opprettet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utlan',
            name='planlagt_retur',
            field=models.DateTimeField(),
        ),
    ]
